---
# This playbook contains common plays that will be run on all nodes.
#- name: Wait for automatic system updates
#  become: yes
#  wait_for: path=/var/lib/dpkg/lock state=absent

- name: Wait for automatic system updates
  become: yes
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;


- name: Wait for automatic system updates
  become: yes
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;


- name: Wait for automatic system updates
  become: yes
  shell: while sudo fuser /var/lib/apt/lists/ >/dev/null 2>&1; do sleep 1; done;

- name: Update all packages to the latest version
  apt:
    name: aptitude
  delay: 6
  retries: 10
#    upgrade: yes

#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

- name: Install ntp
  yum: name=ntp state=latest
  tags: ntp
  register: ntp_install

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  when: ntp_install.changed
  tags: ntp


#- name: test to see if selinux is running
#  command: getenforce
#  register: sestatus
#  changed_when: false
